/**
 * LINE Messaging API
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

//go:generate python3 ../../generate-code.py
package messaging_api

import (
	"encoding/json"
	"fmt"
)

type SubstitutionObjectInterface interface {
	GetType() string
}

func (e SubstitutionObject) GetType() string {
	return e.Type
}

type UnknownSubstitutionObject struct {
	SubstitutionObjectInterface
	Type string
	Raw  map[string]json.RawMessage
}

func (e UnknownSubstitutionObject) GetType() string {
	return e.Type
}

func setDiscriminatorPropertySubstitutionObject(r SubstitutionObjectInterface) SubstitutionObjectInterface {
	switch v := r.(type) {
	case *EmojiSubstitutionObject:
		if v.Type == "" {
			v.Type = "emoji"
		}
		return v
	case EmojiSubstitutionObject:
		if v.Type == "" {
			v.Type = "emoji"
		}
		return v
	case *MentionSubstitutionObject:
		if v.Type == "" {
			v.Type = "mention"
		}
		return v
	case MentionSubstitutionObject:
		if v.Type == "" {
			v.Type = "mention"
		}
		return v

	default:
		return v
	}
}

// SubstitutionObject
// An object that defines the replacement value for a placeholder in the text.

type SubstitutionObject struct {
	// Type of substitution object

	Type string `json:"type"`
}

func UnmarshalSubstitutionObject(data []byte) (SubstitutionObjectInterface, error) {
	var raw map[string]json.RawMessage
	err := json.Unmarshal(data, &raw)
	if err != nil {
		return nil, fmt.Errorf("UnmarshalSubstitutionObject: %w", err)
	}

	var discriminator string
	err = json.Unmarshal(raw["type"], &discriminator)
	if err != nil {
		return nil, fmt.Errorf("UnmarshalSubstitutionObject: Cannot read type: %w", err)
	}

	switch discriminator {
	case "emoji":
		var emoji EmojiSubstitutionObject
		if err := json.Unmarshal(data, &emoji); err != nil {
			return nil, fmt.Errorf("UnmarshalSubstitutionObject: Cannot read emoji: %w", err)
		}
		return emoji, nil
	case "mention":
		var mention MentionSubstitutionObject
		if err := json.Unmarshal(data, &mention); err != nil {
			return nil, fmt.Errorf("UnmarshalSubstitutionObject: Cannot read mention: %w", err)
		}
		return mention, nil

	default:
		var unknown UnknownSubstitutionObject
		unknown.Type = discriminator
		unknown.Raw = raw
		return unknown, nil
	}
}
