/**
 * LINE Messaging API
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

//go:generate python3 ../../generate-code.py
package messaging_api

import (
	"encoding/json"
)

// DatetimePickerAction
// DatetimePickerAction
// https://developers.line.biz/en/reference/messaging-api/#datetime-picker-action
// Deprecated: Use OpenAPI based classes instead.
type DatetimePickerAction struct {
	Action

	/**
	 * Label for the action.
	 */
	Label string `json:"label,omitempty"`

	/**
	 * Get Data
	 */
	Data string `json:"data,omitempty"`

	/**
	 * Get Mode
	 */
	Mode DatetimePickerActionMODE `json:"mode,omitempty"`

	/**
	 * Get Initial
	 */
	Initial string `json:"initial,omitempty"`

	/**
	 * Get Max
	 */
	Max string `json:"max,omitempty"`

	/**
	 * Get Min
	 */
	Min string `json:"min,omitempty"`
}

// MarshalJSON customizes the JSON serialization of the DatetimePickerAction struct.
func (r *DatetimePickerAction) MarshalJSON() ([]byte, error) {

	type Alias DatetimePickerAction
	return json.Marshal(&struct {
		*Alias

		Type string `json:"type,omitempty"`
	}{
		Alias: (*Alias)(r),

		Type: "datetimepicker",
	})
}

// DatetimePickerActionMODE type

type DatetimePickerActionMODE string

// DatetimePickerActionMODE constants
const (
	DatetimePickerActionMODE_DATE DatetimePickerActionMODE = "date"

	DatetimePickerActionMODE_TIME DatetimePickerActionMODE = "time"

	DatetimePickerActionMODE_DATETIME DatetimePickerActionMODE = "datetime"
)
