/**
 * LINE Messaging API
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

//go:generate python3 ../../generate-code.py
package messaging_api

import (
	"encoding/json"
)

// NormalAcquisitionConditionRequest
// NormalAcquisitionConditionRequest

type NormalAcquisitionConditionRequest struct {
	AcquisitionConditionRequest
}

// MarshalJSON customizes the JSON serialization of the NormalAcquisitionConditionRequest struct.
func (r *NormalAcquisitionConditionRequest) MarshalJSON() ([]byte, error) {

	type Alias NormalAcquisitionConditionRequest
	return json.Marshal(&struct {
		*Alias

		Type string `json:"type"`
	}{
		Alias: (*Alias)(r),

		Type: "normal",
	})
}
