/**
 * LINE Messaging API
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

//go:generate python3 ../../generate-code.py
package messaging_api

// RichMenuAliasResponse
// RichMenuAliasResponse

type RichMenuAliasResponse struct {

	/**
	 * Rich menu alias ID. (Required)
	 */
	RichMenuAliasId string `json:"richMenuAliasId"`

	/**
	 * The rich menu ID associated with the rich menu alias. (Required)
	 */
	RichMenuId string `json:"richMenuId"`
}

func NewRichMenuAliasResponse(

	RichMenuAliasId string,

	RichMenuId string,

) *RichMenuAliasResponse {
	e := &RichMenuAliasResponse{}

	e.RichMenuAliasId = RichMenuAliasId

	e.RichMenuId = RichMenuId

	return e
}
