/**
 * LINE Messaging API
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

//go:generate python3 ../../generate-code.py
package messaging_api

import (
	"encoding/json"
	"fmt"
)

type AcquisitionConditionRequestInterface interface {
	GetType() string
}

func (e AcquisitionConditionRequest) GetType() string {
	return e.Type
}

type UnknownAcquisitionConditionRequest struct {
	AcquisitionConditionRequestInterface
	Type string
	Raw  map[string]json.RawMessage
}

func (e UnknownAcquisitionConditionRequest) GetType() string {
	return e.Type
}

func setDiscriminatorPropertyAcquisitionConditionRequest(r AcquisitionConditionRequestInterface) AcquisitionConditionRequestInterface {
	switch v := r.(type) {
	case *LotteryAcquisitionConditionRequest:
		if v.Type == "" {
			v.Type = "lottery"
		}
		return v
	case LotteryAcquisitionConditionRequest:
		if v.Type == "" {
			v.Type = "lottery"
		}
		return v
	case *NormalAcquisitionConditionRequest:
		if v.Type == "" {
			v.Type = "normal"
		}
		return v
	case NormalAcquisitionConditionRequest:
		if v.Type == "" {
			v.Type = "normal"
		}
		return v

	default:
		return v
	}
}

// AcquisitionConditionRequest

type AcquisitionConditionRequest struct {
	// Determines how the coupon is distributed or used.

	Type string `json:"type"`
}

func UnmarshalAcquisitionConditionRequest(data []byte) (AcquisitionConditionRequestInterface, error) {
	var raw map[string]json.RawMessage
	err := json.Unmarshal(data, &raw)
	if err != nil {
		return nil, fmt.Errorf("UnmarshalAcquisitionConditionRequest: %w", err)
	}

	var discriminator string
	err = json.Unmarshal(raw["type"], &discriminator)
	if err != nil {
		return nil, fmt.Errorf("UnmarshalAcquisitionConditionRequest: Cannot read type: %w", err)
	}

	switch discriminator {
	case "lottery":
		var lottery LotteryAcquisitionConditionRequest
		if err := json.Unmarshal(data, &lottery); err != nil {
			return nil, fmt.Errorf("UnmarshalAcquisitionConditionRequest: Cannot read lottery: %w", err)
		}
		return lottery, nil
	case "normal":
		var normal NormalAcquisitionConditionRequest
		if err := json.Unmarshal(data, &normal); err != nil {
			return nil, fmt.Errorf("UnmarshalAcquisitionConditionRequest: Cannot read normal: %w", err)
		}
		return normal, nil

	default:
		var unknown UnknownAcquisitionConditionRequest
		unknown.Type = discriminator
		unknown.Raw = raw
		return unknown, nil
	}
}
