/**
 * LINE Messaging API
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

//go:generate python3 ../../generate-code.py
package messaging_api

import (
	"encoding/json"
	"fmt"
)

type DiscountPriceInfoRequestInterface interface {
	GetType() string
}

func (e DiscountPriceInfoRequest) GetType() string {
	return e.Type
}

type UnknownDiscountPriceInfoRequest struct {
	DiscountPriceInfoRequestInterface
	Type string
	Raw  map[string]json.RawMessage
}

func (e UnknownDiscountPriceInfoRequest) GetType() string {
	return e.Type
}

func setDiscriminatorPropertyDiscountPriceInfoRequest(r DiscountPriceInfoRequestInterface) DiscountPriceInfoRequestInterface {
	switch v := r.(type) {
	case *DiscountExplicitPriceInfoRequest:
		if v.Type == "" {
			v.Type = "explicit"
		}
		return v
	case DiscountExplicitPriceInfoRequest:
		if v.Type == "" {
			v.Type = "explicit"
		}
		return v
	case *DiscountFixedPriceInfoRequest:
		if v.Type == "" {
			v.Type = "fixed"
		}
		return v
	case DiscountFixedPriceInfoRequest:
		if v.Type == "" {
			v.Type = "fixed"
		}
		return v
	case *DiscountPercentagePriceInfoRequest:
		if v.Type == "" {
			v.Type = "percentage"
		}
		return v
	case DiscountPercentagePriceInfoRequest:
		if v.Type == "" {
			v.Type = "percentage"
		}
		return v

	default:
		return v
	}
}

// DiscountPriceInfoRequest

type DiscountPriceInfoRequest struct {
	Type string `json:"type"`
}

func UnmarshalDiscountPriceInfoRequest(data []byte) (DiscountPriceInfoRequestInterface, error) {
	var raw map[string]json.RawMessage
	err := json.Unmarshal(data, &raw)
	if err != nil {
		return nil, fmt.Errorf("UnmarshalDiscountPriceInfoRequest: %w", err)
	}

	var discriminator string
	err = json.Unmarshal(raw["type"], &discriminator)
	if err != nil {
		return nil, fmt.Errorf("UnmarshalDiscountPriceInfoRequest: Cannot read type: %w", err)
	}

	switch discriminator {
	case "explicit":
		var explicit DiscountExplicitPriceInfoRequest
		if err := json.Unmarshal(data, &explicit); err != nil {
			return nil, fmt.Errorf("UnmarshalDiscountPriceInfoRequest: Cannot read explicit: %w", err)
		}
		return explicit, nil
	case "fixed":
		var fixed DiscountFixedPriceInfoRequest
		if err := json.Unmarshal(data, &fixed); err != nil {
			return nil, fmt.Errorf("UnmarshalDiscountPriceInfoRequest: Cannot read fixed: %w", err)
		}
		return fixed, nil
	case "percentage":
		var percentage DiscountPercentagePriceInfoRequest
		if err := json.Unmarshal(data, &percentage); err != nil {
			return nil, fmt.Errorf("UnmarshalDiscountPriceInfoRequest: Cannot read percentage: %w", err)
		}
		return percentage, nil

	default:
		var unknown UnknownDiscountPriceInfoRequest
		unknown.Type = discriminator
		unknown.Raw = raw
		return unknown, nil
	}
}
