/**
 * LINE Messaging API
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

//go:generate python3 ../../generate-code.py
package messaging_api

// AppTypeDemographic type
type AppTypeDemographic string

// AppTypeDemographic constants
const (
	AppTypeDemographic_IOS AppTypeDemographic = "iosaa"

	AppTypeDemographic_ANDROID AppTypeDemographic = "android"
)
