/**
 * LINE Messaging API
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

//go:generate python3 ../../generate-code.py
package messaging_api

/*
 * You can specify the minimum space before a child component with the `margin` property of the child component, in pixels or with a keyword.  FlexMargin just provides only keywords.
 */

// FlexMargin type
type FlexMargin string

// FlexMargin constants
const (
	FlexMargin_NONE FlexMargin = "none"

	FlexMargin_XS FlexMargin = "xs"

	FlexMargin_SM FlexMargin = "sm"

	FlexMargin_MD FlexMargin = "md"

	FlexMargin_LG FlexMargin = "lg"

	FlexMargin_XL FlexMargin = "xl"

	FlexMargin_XXL FlexMargin = "xxl"
)
