/**
 * LINE Messaging API
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

//go:generate python3 ../../generate-code.py
package messaging_api

import (
	"encoding/json"
)

// DiscountExplicitPriceInfoResponse
// DiscountExplicitPriceInfoResponse

type DiscountExplicitPriceInfoResponse struct {
	DiscountPriceInfoResponse

	/**
	 * Currency code (e.g., JPY, THB, TWD).
	 */
	Currency DiscountExplicitPriceInfoResponseCURRENCY `json:"currency,omitempty"`

	/**
	 * Get PriceAfterDiscount
	 */
	PriceAfterDiscount int64 `json:"priceAfterDiscount"`

	/**
	 * Get OriginalPrice
	 */
	OriginalPrice int64 `json:"originalPrice"`
}

// MarshalJSON customizes the JSON serialization of the DiscountExplicitPriceInfoResponse struct.
func (r *DiscountExplicitPriceInfoResponse) MarshalJSON() ([]byte, error) {

	type Alias DiscountExplicitPriceInfoResponse
	return json.Marshal(&struct {
		*Alias

		Type string `json:"type"`
	}{
		Alias: (*Alias)(r),

		Type: "explicit",
	})
}

// DiscountExplicitPriceInfoResponseCURRENCY type
/* Currency code (e.g., JPY, THB, TWD). */
type DiscountExplicitPriceInfoResponseCURRENCY string

// DiscountExplicitPriceInfoResponseCURRENCY constants
const (
	DiscountExplicitPriceInfoResponseCURRENCY_JPY DiscountExplicitPriceInfoResponseCURRENCY = "JPY"

	DiscountExplicitPriceInfoResponseCURRENCY_THB DiscountExplicitPriceInfoResponseCURRENCY = "THB"

	DiscountExplicitPriceInfoResponseCURRENCY_TWD DiscountExplicitPriceInfoResponseCURRENCY = "TWD"
)
