/**
 * LINE Messaging API
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

//go:generate python3 ../../generate-code.py
package messaging_api

import (
	"encoding/json"
)

// LotteryAcquisitionConditionResponse
// LotteryAcquisitionConditionResponse

type LotteryAcquisitionConditionResponse struct {
	AcquisitionConditionResponse

	/**
	 * Get LotteryProbability
	 */
	LotteryProbability int32 `json:"lotteryProbability"`

	/**
	 * Get MaxAcquireCount
	 */
	MaxAcquireCount int32 `json:"maxAcquireCount"`
}

// MarshalJSON customizes the JSON serialization of the LotteryAcquisitionConditionResponse struct.
func (r *LotteryAcquisitionConditionResponse) MarshalJSON() ([]byte, error) {

	type Alias LotteryAcquisitionConditionResponse
	return json.Marshal(&struct {
		*Alias

		Type string `json:"type"`
	}{
		Alias: (*Alias)(r),

		Type: "lottery",
	})
}
