/**
 * LINE Messaging API
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

//go:generate python3 ../../generate-code.py
package messaging_api

import (
	"encoding/json"
)

// CashBackFixedPriceInfoResponse
// CashBackFixedPriceInfoResponse

type CashBackFixedPriceInfoResponse struct {
	CashBackPriceInfoResponse

	/**
	 * Currency code (e.g., JPY, THB, TWD).
	 */
	Currency CashBackFixedPriceInfoResponseCURRENCY `json:"currency,omitempty"`

	/**
	 * Get FixedAmount
	 */
	FixedAmount int64 `json:"fixedAmount"`
}

// MarshalJSON customizes the JSON serialization of the CashBackFixedPriceInfoResponse struct.
func (r *CashBackFixedPriceInfoResponse) MarshalJSON() ([]byte, error) {

	type Alias CashBackFixedPriceInfoResponse
	return json.Marshal(&struct {
		*Alias

		Type string `json:"type"`
	}{
		Alias: (*Alias)(r),

		Type: "fixed",
	})
}

// CashBackFixedPriceInfoResponseCURRENCY type
/* Currency code (e.g., JPY, THB, TWD). */
type CashBackFixedPriceInfoResponseCURRENCY string

// CashBackFixedPriceInfoResponseCURRENCY constants
const (
	CashBackFixedPriceInfoResponseCURRENCY_JPY CashBackFixedPriceInfoResponseCURRENCY = "JPY"

	CashBackFixedPriceInfoResponseCURRENCY_THB CashBackFixedPriceInfoResponseCURRENCY = "THB"

	CashBackFixedPriceInfoResponseCURRENCY_TWD CashBackFixedPriceInfoResponseCURRENCY = "TWD"
)
