/**
 * LINE Messaging API
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

//go:generate python3 ../../generate-code.py
package messaging_api

import (
	"time"
)

// RichMenuBatchProgressResponse
// RichMenuBatchProgressResponse
// https://developers.line.biz/en/reference/messaging-api/#get-batch-control-rich-menus-progress-status-response
type RichMenuBatchProgressResponse struct {

	/**
	 * Get Phase
	 */
	Phase RichMenuBatchProgressPhase `json:"phase"`

	/**
	 * The accepted time in milliseconds of the request of batch control the rich menu.  Format: ISO 8601 (e.g. 2023-06-08T10:15:30.121Z) Timezone: UTC  (Required)
	 */
	AcceptedTime time.Time `json:"acceptedTime"`

	/**
	 * The completed time in milliseconds of rich menu batch control. Returned when the phase property is succeeded or failed.  Format: ISO 8601 (e.g. 2023-06-08T10:15:30.121Z) Timezone: UTC
	 */
	CompletedTime time.Time `json:"completedTime,omitempty"`
}

func NewRichMenuBatchProgressResponse(

	Phase RichMenuBatchProgressPhase,

	AcceptedTime time.Time,

) *RichMenuBatchProgressResponse {
	e := &RichMenuBatchProgressResponse{}

	e.Phase = Phase

	e.AcceptedTime = AcceptedTime

	return e
}
