/**
 * LINE Messaging API
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

//go:generate python3 ../../generate-code.py
package messaging_api

import (
	"encoding/json"
)

// FlexText
// FlexText

// Deprecated: Use OpenAPI based classes instead.
type FlexText struct {
	FlexComponent

	/**
	 * Get Flex
	 */
	Flex int32 `json:"flex"`

	/**
	 * Get Text
	 */
	Text string `json:"text,omitempty"`

	/**
	 * Get Size
	 */
	Size string `json:"size,omitempty"`

	/**
	 * Get Align
	 */
	Align FlexTextALIGN `json:"align,omitempty"`

	/**
	 * Get Gravity
	 */
	Gravity FlexTextGRAVITY `json:"gravity,omitempty"`

	/**
	 * Get Color
	 */
	Color string `json:"color,omitempty"`

	/**
	 * Get Weight
	 */
	Weight FlexTextWEIGHT `json:"weight,omitempty"`

	/**
	 * Get Style
	 */
	Style FlexTextSTYLE `json:"style,omitempty"`

	/**
	 * Get Decoration
	 */
	Decoration FlexTextDECORATION `json:"decoration,omitempty"`

	/**
	 * Get Wrap
	 */
	Wrap bool `json:"wrap"`

	/**
	 * Get LineSpacing
	 */
	LineSpacing string `json:"lineSpacing,omitempty"`

	/**
	 * Get Margin
	 */
	Margin string `json:"margin,omitempty"`

	/**
	 * Get Position
	 */
	Position FlexTextPOSITION `json:"position,omitempty"`

	/**
	 * Get OffsetTop
	 */
	OffsetTop string `json:"offsetTop,omitempty"`

	/**
	 * Get OffsetBottom
	 */
	OffsetBottom string `json:"offsetBottom,omitempty"`

	/**
	 * Get OffsetStart
	 */
	OffsetStart string `json:"offsetStart,omitempty"`

	/**
	 * Get OffsetEnd
	 */
	OffsetEnd string `json:"offsetEnd,omitempty"`

	/**
	 * Get Action
	 */
	Action ActionInterface `json:"action,omitempty"`

	/**
	 * Get MaxLines
	 */
	MaxLines int32 `json:"maxLines"`

	/**
	 * Get Contents
	 */
	Contents []FlexSpan `json:"contents,omitempty"`

	/**
	 * Get AdjustMode
	 */
	AdjustMode FlexTextADJUST_MODE `json:"adjustMode,omitempty"`

	/**
	 * Get Scaling
	 */
	Scaling bool `json:"scaling"`
}

func (cr *FlexText) UnmarshalJSON(data []byte) error {
	var raw map[string]json.RawMessage
	err := json.Unmarshal(data, &raw)
	if err != nil {
		return err
	}

	err = json.Unmarshal(raw["type"], &cr.Type)
	if err != nil {
		return err
	}

	err = json.Unmarshal(raw["flex"], &cr.Flex)
	if err != nil {
		return err
	}

	err = json.Unmarshal(raw["text"], &cr.Text)
	if err != nil {
		return err
	}

	err = json.Unmarshal(raw["size"], &cr.Size)
	if err != nil {
		return err
	}

	err = json.Unmarshal(raw["align"], &cr.Align)
	if err != nil {
		return err
	}

	err = json.Unmarshal(raw["gravity"], &cr.Gravity)
	if err != nil {
		return err
	}

	err = json.Unmarshal(raw["color"], &cr.Color)
	if err != nil {
		return err
	}

	err = json.Unmarshal(raw["weight"], &cr.Weight)
	if err != nil {
		return err
	}

	err = json.Unmarshal(raw["style"], &cr.Style)
	if err != nil {
		return err
	}

	err = json.Unmarshal(raw["decoration"], &cr.Decoration)
	if err != nil {
		return err
	}

	err = json.Unmarshal(raw["wrap"], &cr.Wrap)
	if err != nil {
		return err
	}

	err = json.Unmarshal(raw["lineSpacing"], &cr.LineSpacing)
	if err != nil {
		return err
	}

	err = json.Unmarshal(raw["margin"], &cr.Margin)
	if err != nil {
		return err
	}

	err = json.Unmarshal(raw["position"], &cr.Position)
	if err != nil {
		return err
	}

	err = json.Unmarshal(raw["offsetTop"], &cr.OffsetTop)
	if err != nil {
		return err
	}

	err = json.Unmarshal(raw["offsetBottom"], &cr.OffsetBottom)
	if err != nil {
		return err
	}

	err = json.Unmarshal(raw["offsetStart"], &cr.OffsetStart)
	if err != nil {
		return err
	}

	err = json.Unmarshal(raw["offsetEnd"], &cr.OffsetEnd)
	if err != nil {
		return err
	}

	if rawaction, ok := raw["action"]; ok && rawaction != nil {
		Action, err := UnmarshalAction(rawaction)
		if err != nil {
			return err
		}
		cr.Action = Action
	}

	err = json.Unmarshal(raw["maxLines"], &cr.MaxLines)
	if err != nil {
		return err
	}

	err = json.Unmarshal(raw["contents"], &cr.Contents)
	if err != nil {
		return err
	}

	err = json.Unmarshal(raw["adjustMode"], &cr.AdjustMode)
	if err != nil {
		return err
	}

	err = json.Unmarshal(raw["scaling"], &cr.Scaling)
	if err != nil {
		return err
	}

	return nil
}

// MarshalJSON customizes the JSON serialization of the FlexText struct.
func (r *FlexText) MarshalJSON() ([]byte, error) {

	r.Action = setDiscriminatorPropertyAction(r.Action)

	type Alias FlexText
	return json.Marshal(&struct {
		*Alias

		Type string `json:"type"`
	}{
		Alias: (*Alias)(r),

		Type: "text",
	})
}

// FlexTextALIGN type

type FlexTextALIGN string

// FlexTextALIGN constants
const (
	FlexTextALIGN_START FlexTextALIGN = "start"

	FlexTextALIGN_END FlexTextALIGN = "end"

	FlexTextALIGN_CENTER FlexTextALIGN = "center"
)

// FlexTextGRAVITY type

type FlexTextGRAVITY string

// FlexTextGRAVITY constants
const (
	FlexTextGRAVITY_TOP FlexTextGRAVITY = "top"

	FlexTextGRAVITY_BOTTOM FlexTextGRAVITY = "bottom"

	FlexTextGRAVITY_CENTER FlexTextGRAVITY = "center"
)

// FlexTextWEIGHT type

type FlexTextWEIGHT string

// FlexTextWEIGHT constants
const (
	FlexTextWEIGHT_REGULAR FlexTextWEIGHT = "regular"

	FlexTextWEIGHT_BOLD FlexTextWEIGHT = "bold"
)

// FlexTextSTYLE type

type FlexTextSTYLE string

// FlexTextSTYLE constants
const (
	FlexTextSTYLE_NORMAL FlexTextSTYLE = "normal"

	FlexTextSTYLE_ITALIC FlexTextSTYLE = "italic"
)

// FlexTextDECORATION type

type FlexTextDECORATION string

// FlexTextDECORATION constants
const (
	FlexTextDECORATION_NONE FlexTextDECORATION = "none"

	FlexTextDECORATION_UNDERLINE FlexTextDECORATION = "underline"

	FlexTextDECORATION_LINE_THROUGH FlexTextDECORATION = "line-through"
)

// FlexTextPOSITION type

type FlexTextPOSITION string

// FlexTextPOSITION constants
const (
	FlexTextPOSITION_RELATIVE FlexTextPOSITION = "relative"

	FlexTextPOSITION_ABSOLUTE FlexTextPOSITION = "absolute"
)

// FlexTextADJUST_MODE type

type FlexTextADJUST_MODE string

// FlexTextADJUST_MODE constants
const (
	FlexTextADJUST_MODE_SHRINK_TO_FIT FlexTextADJUST_MODE = "shrink-to-fit"
)
