/**
 * LINE Messaging API
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

//go:generate python3 ../../generate-code.py
package messaging_api

import (
	"encoding/json"
)

// UriAction
// UriAction

// Deprecated: Use OpenAPI based classes instead.
type UriAction struct {
	Action

	/**
	 * Label for the action.
	 */
	Label string `json:"label,omitempty"`

	/**
	 * Get Uri
	 */
	Uri string `json:"uri,omitempty"`

	/**
	 * Get AltUri
	 */
	AltUri *AltUri `json:"altUri,omitempty"`
}

// MarshalJSON customizes the JSON serialization of the UriAction struct.
func (r *UriAction) MarshalJSON() ([]byte, error) {

	type Alias UriAction
	return json.Marshal(&struct {
		*Alias

		Type string `json:"type,omitempty"`
	}{
		Alias: (*Alias)(r),

		Type: "uri",
	})
}
