/**
 * LINE Messaging API
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

//go:generate python3 ../../generate-code.py
package messaging_api

// RichMenuListResponse
// RichMenuListResponse
// https://developers.line.biz/en/reference/messaging-api/#get-rich-menu-list
type RichMenuListResponse struct {

	/**
	 * Rich menus (Required)
	 */
	Richmenus []RichMenuResponse `json:"richmenus"`
}

func NewRichMenuListResponse(

	Richmenus []RichMenuResponse,

) *RichMenuListResponse {
	e := &RichMenuListResponse{}

	e.Richmenus = Richmenus

	return e
}
