/**
 * LINE Messaging API
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

//go:generate python3 ../../generate-code.py
package messaging_api

import (
	"encoding/json"
)

// ClipboardImagemapAction
// ClipboardImagemapAction
// https://developers.line.biz/en/reference/messaging-api/#imagemap-clipboard-action-object
type ClipboardImagemapAction struct {
	ImagemapAction

	/**
	 * Get Area
	 */
	Area *ImagemapArea `json:"area"`

	/**
	 * Text that is copied to the clipboard. Max character limit: 1000  (Required)
	 */
	ClipboardText string `json:"clipboardText"`

	/**
	 * Get Label
	 */
	Label string `json:"label,omitempty"`
}

// MarshalJSON customizes the JSON serialization of the ClipboardImagemapAction struct.
func (r *ClipboardImagemapAction) MarshalJSON() ([]byte, error) {

	type Alias ClipboardImagemapAction
	return json.Marshal(&struct {
		*Alias

		Type string `json:"type"`
	}{
		Alias: (*Alias)(r),

		Type: "clipboard",
	})
}
