/**
 * LINE Messaging API
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

//go:generate python3 ../../generate-code.py
package messaging_api

// GetAggregationUnitUsageResponse
// GetAggregationUnitUsageResponse
// https://developers.line.biz/en/reference/messaging-api/#get-number-of-units-used-this-month
type GetAggregationUnitUsageResponse struct {

	/**
	 * Number of aggregation units used this month. (Required)
	 */
	NumOfCustomAggregationUnits int64 `json:"numOfCustomAggregationUnits"`
}

func NewGetAggregationUnitUsageResponse(

	NumOfCustomAggregationUnits int64,

) *GetAggregationUnitUsageResponse {
	e := &GetAggregationUnitUsageResponse{}

	e.NumOfCustomAggregationUnits = NumOfCustomAggregationUnits

	return e
}
