/**
 * LINE Messaging API
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

//go:generate python3 ../../generate-code.py
package messaging_api

// GetAggregationUnitNameListResponse
// GetAggregationUnitNameListResponse
// https://developers.line.biz/en/reference/messaging-api/#get-name-list-of-units-used-this-month
type GetAggregationUnitNameListResponse struct {

	/**
	 * An array of strings indicating the names of aggregation units used this month. (Required)
	 */
	CustomAggregationUnits []string `json:"customAggregationUnits"`

	/**
	 * A continuation token to get the next array of unit names. Returned only when there are remaining aggregation units that weren&#39;t returned in customAggregationUnits in the original request.
	 */
	Next string `json:"next,omitempty"`
}

func NewGetAggregationUnitNameListResponse(

	CustomAggregationUnits []string,

) *GetAggregationUnitNameListResponse {
	e := &GetAggregationUnitNameListResponse{}

	e.CustomAggregationUnits = CustomAggregationUnits

	return e
}
