/**
 * LINE Messaging API
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

//go:generate python3 ../../generate-code.py
package messaging_api

import (
	"encoding/json"
)

// DiscountFixedPriceInfoResponse
// DiscountFixedPriceInfoResponse

type DiscountFixedPriceInfoResponse struct {
	DiscountPriceInfoResponse

	/**
	 * Currency code (e.g., JPY, THB, TWD).
	 */
	Currency DiscountFixedPriceInfoResponseCURRENCY `json:"currency,omitempty"`

	/**
	 * Get FixedAmount
	 */
	FixedAmount int64 `json:"fixedAmount"`
}

// MarshalJSON customizes the JSON serialization of the DiscountFixedPriceInfoResponse struct.
func (r *DiscountFixedPriceInfoResponse) MarshalJSON() ([]byte, error) {

	type Alias DiscountFixedPriceInfoResponse
	return json.Marshal(&struct {
		*Alias

		Type string `json:"type"`
	}{
		Alias: (*Alias)(r),

		Type: "fixed",
	})
}

// DiscountFixedPriceInfoResponseCURRENCY type
/* Currency code (e.g., JPY, THB, TWD). */
type DiscountFixedPriceInfoResponseCURRENCY string

// DiscountFixedPriceInfoResponseCURRENCY constants
const (
	DiscountFixedPriceInfoResponseCURRENCY_JPY DiscountFixedPriceInfoResponseCURRENCY = "JPY"

	DiscountFixedPriceInfoResponseCURRENCY_THB DiscountFixedPriceInfoResponseCURRENCY = "THB"

	DiscountFixedPriceInfoResponseCURRENCY_TWD DiscountFixedPriceInfoResponseCURRENCY = "TWD"
)
