/**
 * LINE Messaging API
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

//go:generate python3 ../../generate-code.py
package messaging_api

import (
	"encoding/json"
)

// CashBackPercentagePriceInfoRequest
// CashBackPercentagePriceInfoRequest

type CashBackPercentagePriceInfoRequest struct {
	CashBackPriceInfoRequest

	/**
	 * Specifies the cashback rate as a percentage. Must be an integer between 1 and 99.
	 * minimum: 1
	 * maximum: 99
	 */
	Percentage int32 `json:"percentage,omitempty"`
}

// MarshalJSON customizes the JSON serialization of the CashBackPercentagePriceInfoRequest struct.
func (r *CashBackPercentagePriceInfoRequest) MarshalJSON() ([]byte, error) {

	type Alias CashBackPercentagePriceInfoRequest
	return json.Marshal(&struct {
		*Alias

		Type string `json:"type"`
	}{
		Alias: (*Alias)(r),

		Type: "percentage",
	})
}
