/**
 * LINE Messaging API
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

//go:generate python3 ../../generate-code.py
package messaging_api

// SentMessage
// SentMessage

type SentMessage struct {

	/**
	 * ID of the sent message. (Required)
	 */
	Id string `json:"id"`

	/**
	 * Quote token of the message. Only included when a message object that can be specified as a quote target was sent as a push or reply message.
	 */
	QuoteToken string `json:"quoteToken,omitempty"`
}

func NewSentMessage(

	Id string,

) *SentMessage {
	e := &SentMessage{}

	e.Id = Id

	return e
}
