/**
 * LINE Messaging API
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

//go:generate python3 ../../generate-code.py
package messaging_api

import (
	"encoding/json"
)

// AllMentionTarget
// AllMentionTarget
// https://developers.line.biz/en/reference/messaging-api/#text-message-v2-mentionee-all
type AllMentionTarget struct {
	MentionTarget
}

// MarshalJSON customizes the JSON serialization of the AllMentionTarget struct.
func (r *AllMentionTarget) MarshalJSON() ([]byte, error) {

	type Alias AllMentionTarget
	return json.Marshal(&struct {
		*Alias

		Type string `json:"type"`
	}{
		Alias: (*Alias)(r),

		Type: "all",
	})
}
