/**
 * LINE Messaging API
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

//go:generate python3 ../../generate-code.py
package messaging_api

/*
 * You can specify the minimum space between two components with the `spacing` property of the parent box component, in pixels or with a keyword. FlexBoxSpacing just provides only keywords.
 */

// FlexBoxSpacing type
type FlexBoxSpacing string

// FlexBoxSpacing constants
const (
	FlexBoxSpacing_NONE FlexBoxSpacing = "none"

	FlexBoxSpacing_XS FlexBoxSpacing = "xs"

	FlexBoxSpacing_SM FlexBoxSpacing = "sm"

	FlexBoxSpacing_MD FlexBoxSpacing = "md"

	FlexBoxSpacing_LG FlexBoxSpacing = "lg"

	FlexBoxSpacing_XL FlexBoxSpacing = "xl"

	FlexBoxSpacing_XXL FlexBoxSpacing = "xxl"
)
