/**
 * LINE Messaging API
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

//go:generate python3 ../../generate-code.py
package messaging_api

import (
	"encoding/json"
)

// UserMentionTarget
// UserMentionTarget
// https://developers.line.biz/en/reference/messaging-api/#text-message-v2-mentionee-user
type UserMentionTarget struct {
	MentionTarget

	/**
	 * Get UserId
	 */
	UserId string `json:"userId"`
}

// MarshalJSON customizes the JSON serialization of the UserMentionTarget struct.
func (r *UserMentionTarget) MarshalJSON() ([]byte, error) {

	type Alias UserMentionTarget
	return json.Marshal(&struct {
		*Alias

		Type string `json:"type"`
	}{
		Alias: (*Alias)(r),

		Type: "user",
	})
}
