/**
 * LINE Messaging API
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

//go:generate python3 ../../generate-code.py
package messaging_api

import (
	"encoding/json"
)

// LotteryAcquisitionConditionRequest
// LotteryAcquisitionConditionRequest

type LotteryAcquisitionConditionRequest struct {
	AcquisitionConditionRequest

	/**
	 * Probability (1-99) of winning the coupon in lottery-type campaigns. (Required)
	 * minimum: 1
	 * maximum: 99
	 */
	LotteryProbability int32 `json:"lotteryProbability"`

	/**
	 * Maximum number of coupons that can be issued in total. Use -1 to indicate no limit (Required)
	 * maximum: 999999
	 */
	MaxAcquireCount int32 `json:"maxAcquireCount"`
}

// MarshalJSON customizes the JSON serialization of the LotteryAcquisitionConditionRequest struct.
func (r *LotteryAcquisitionConditionRequest) MarshalJSON() ([]byte, error) {

	type Alias LotteryAcquisitionConditionRequest
	return json.Marshal(&struct {
		*Alias

		Type string `json:"type"`
	}{
		Alias: (*Alias)(r),

		Type: "lottery",
	})
}
