/**
 * LINE Messaging API
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

//go:generate python3 ../../generate-code.py
package messaging_api

// GetMessageContentTranscodingResponse
// Transcoding response
// https://developers.line.biz/en/reference/messaging-api/#verify-video-or-audio-preparation-status
// Deprecated: Use OpenAPI based classes instead.
type GetMessageContentTranscodingResponse struct {

	/**
	 * The preparation status. One of:  `processing`: Preparing to get content. `succeeded`: Ready to get the content. You can get the content sent by users. `failed`: Failed to prepare to get the content.  (Required)
	 */
	Status GetMessageContentTranscodingResponseSTATUS `json:"status"`
}

// GetMessageContentTranscodingResponseSTATUS type
/* The preparation status. One of:  `processing`: Preparing to get content. `succeeded`: Ready to get the content. You can get the content sent by users. `failed`: Failed to prepare to get the content.  */
type GetMessageContentTranscodingResponseSTATUS string

// GetMessageContentTranscodingResponseSTATUS constants
const (
	GetMessageContentTranscodingResponseSTATUS_PROCESSING GetMessageContentTranscodingResponseSTATUS = "processing"

	GetMessageContentTranscodingResponseSTATUS_SUCCEEDED GetMessageContentTranscodingResponseSTATUS = "succeeded"

	GetMessageContentTranscodingResponseSTATUS_FAILED GetMessageContentTranscodingResponseSTATUS = "failed"
)
