/**
 * LINE Messaging API
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

//go:generate python3 ../../generate-code.py
package messaging_api

import (
	"encoding/json"
)

// ImageCarouselTemplate
// ImageCarouselTemplate

type ImageCarouselTemplate struct {
	Template

	/**
	 * Get Columns
	 */
	Columns []ImageCarouselColumn `json:"columns"`
}

func NewImageCarouselTemplate(

	Columns []ImageCarouselColumn,

) *ImageCarouselTemplate {
	e := &ImageCarouselTemplate{}

	e.Type = "image_carousel"

	e.Columns = Columns

	return e
}

// MarshalJSON customizes the JSON serialization of the ImageCarouselTemplate struct.
func (r *ImageCarouselTemplate) MarshalJSON() ([]byte, error) {

	type Alias ImageCarouselTemplate
	return json.Marshal(&struct {
		*Alias

		Type string `json:"type"`
	}{
		Alias: (*Alias)(r),

		Type: "image_carousel",
	})
}
