/**
 * LINE Messaging API
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

//go:generate python3 ../../generate-code.py
package messaging_api

/*
 * Width of box border. This is only for `borderWidth` in FlexBox. A value of none means that borders are not rendered; the other values are listed in order of increasing width.
 */

// FlexBoxBorderWidth type
type FlexBoxBorderWidth string

// FlexBoxBorderWidth constants
const (
	FlexBoxBorderWidth_NONE FlexBoxBorderWidth = "none"

	FlexBoxBorderWidth_LIGHT FlexBoxBorderWidth = "light"

	FlexBoxBorderWidth_NORMAL FlexBoxBorderWidth = "normal"

	FlexBoxBorderWidth_MEDIUM FlexBoxBorderWidth = "medium"

	FlexBoxBorderWidth_SEMI_BOLD FlexBoxBorderWidth = "semi-bold"

	FlexBoxBorderWidth_BOLD FlexBoxBorderWidth = "bold"
)
