/**
 * LINE Messaging API
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

//go:generate python3 ../../generate-code.py
package messaging_api

import (
	"encoding/json"
)

// RichMenuBatchUnlinkOperation
// Unlink the rich menu for all users linked to the rich menu specified in the `from` property.

type RichMenuBatchUnlinkOperation struct {
	RichMenuBatchOperation

	/**
	 * Get From
	 */
	From string `json:"from"`
}

// MarshalJSON customizes the JSON serialization of the RichMenuBatchUnlinkOperation struct.
func (r *RichMenuBatchUnlinkOperation) MarshalJSON() ([]byte, error) {

	type Alias RichMenuBatchUnlinkOperation
	return json.Marshal(&struct {
		*Alias

		Type string `json:"type"`
	}{
		Alias: (*Alias)(r),

		Type: "unlink",
	})
}
