/**
 * LINE Messaging API
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

//go:generate python3 ../../generate-code.py
package messaging_api

/*
 * You can specify the offset of a component with the `offset*` property, in pixels or with a keyword. You can also specify the percentage to the box width for `offsetStart` and `offsetEnd` and to the box height for `offsetTop` and `offsetBottom`. FlexOffset just provides only keywords.
 */

// FlexOffset type
type FlexOffset string

// FlexOffset constants
const (
	FlexOffset_NONE FlexOffset = "none"

	FlexOffset_XS FlexOffset = "xs"

	FlexOffset_SM FlexOffset = "sm"

	FlexOffset_MD FlexOffset = "md"

	FlexOffset_LG FlexOffset = "lg"

	FlexOffset_XL FlexOffset = "xl"

	FlexOffset_XXL FlexOffset = "xxl"
)
