/**
 * LINE Messaging API
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

//go:generate python3 ../../generate-code.py
package messaging_api

import (
	"encoding/json"
	"fmt"
	"log"
)

type FlexBoxBackgroundInterface interface {
	GetType() string
}

func (e FlexBoxBackground) GetType() string {
	return e.Type
}

type UnknownFlexBoxBackground struct {
	FlexBoxBackgroundInterface
	Type string
	Raw  map[string]json.RawMessage
}

func (e UnknownFlexBoxBackground) GetType() string {
	return e.Type
}

func setDiscriminatorPropertyFlexBoxBackground(r FlexBoxBackgroundInterface) FlexBoxBackgroundInterface {
	switch v := r.(type) {
	case *FlexBoxLinearGradient:
		if v.Type == "" {
			v.Type = "linearGradient"
		}
		return v
	case FlexBoxLinearGradient:
		if v.Type == "" {
			v.Type = "linearGradient"
		}
		return v

	default:
		return v
	}
}

// FlexBoxBackground

type FlexBoxBackground struct {
	Type string `json:"type"`
}

func UnmarshalFlexBoxBackground(data []byte) (FlexBoxBackgroundInterface, error) {
	var raw map[string]json.RawMessage
	err := json.Unmarshal(data, &raw)
	if err != nil {
		return nil, fmt.Errorf("UnmarshalFlexBoxBackground: %w", err)
	}

	var discriminator string
	err = json.Unmarshal(raw["type"], &discriminator)
	if err != nil {
		return nil, fmt.Errorf("UnmarshalFlexBoxBackground: Cannot read type: %w", err)
	}

	switch discriminator {
	case "linearGradient":
		var linearGradient FlexBoxLinearGradient
		if err := json.Unmarshal(data, &linearGradient); err != nil {
			return nil, fmt.Errorf("UnmarshalFlexBoxBackground: Cannot read linearGradient: %w", err)
		}
		return linearGradient, nil

	default:
		log.Println("FlexBoxBackground fallback: ", discriminator)
		var unknown UnknownFlexBoxBackground
		unknown.Type = discriminator
		unknown.Raw = raw
		return unknown, nil
	}
}
