/**
 * LINE Messaging API
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

//go:generate python3 ../../generate-code.py
package messaging_api

// FlexBlockStyle
// FlexBlockStyle

// Deprecated: Use OpenAPI based classes instead.
type FlexBlockStyle struct {

	/**
	 * Get BackgroundColor
	 */
	BackgroundColor string `json:"backgroundColor,omitempty"`

	/**
	 * Get Separator
	 */
	Separator bool `json:"separator"`

	/**
	 * Get SeparatorColor
	 */
	SeparatorColor string `json:"separatorColor,omitempty"`
}
