/**
 * LINE Messaging API
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

//go:generate python3 ../../generate-code.py
package messaging_api

import (
	"encoding/json"
	"fmt"
)

type AcquisitionConditionResponseInterface interface {
	GetType() string
}

func (e AcquisitionConditionResponse) GetType() string {
	return e.Type
}

type UnknownAcquisitionConditionResponse struct {
	AcquisitionConditionResponseInterface
	Type string
	Raw  map[string]json.RawMessage
}

func (e UnknownAcquisitionConditionResponse) GetType() string {
	return e.Type
}

func setDiscriminatorPropertyAcquisitionConditionResponse(r AcquisitionConditionResponseInterface) AcquisitionConditionResponseInterface {
	switch v := r.(type) {
	case *LotteryAcquisitionConditionResponse:
		if v.Type == "" {
			v.Type = "lottery"
		}
		return v
	case LotteryAcquisitionConditionResponse:
		if v.Type == "" {
			v.Type = "lottery"
		}
		return v
	case *NormalAcquisitionConditionResponse:
		if v.Type == "" {
			v.Type = "normal"
		}
		return v
	case NormalAcquisitionConditionResponse:
		if v.Type == "" {
			v.Type = "normal"
		}
		return v
	case *ReferralAcquisitionConditionResponse:
		if v.Type == "" {
			v.Type = "referral"
		}
		return v
	case ReferralAcquisitionConditionResponse:
		if v.Type == "" {
			v.Type = "referral"
		}
		return v

	default:
		return v
	}
}

// AcquisitionConditionResponse

type AcquisitionConditionResponse struct {
	// Determines how the coupon is distributed or used.

	Type string `json:"type"`
}

func UnmarshalAcquisitionConditionResponse(data []byte) (AcquisitionConditionResponseInterface, error) {
	var raw map[string]json.RawMessage
	err := json.Unmarshal(data, &raw)
	if err != nil {
		return nil, fmt.Errorf("UnmarshalAcquisitionConditionResponse: %w", err)
	}

	var discriminator string
	err = json.Unmarshal(raw["type"], &discriminator)
	if err != nil {
		return nil, fmt.Errorf("UnmarshalAcquisitionConditionResponse: Cannot read type: %w", err)
	}

	switch discriminator {
	case "lottery":
		var lottery LotteryAcquisitionConditionResponse
		if err := json.Unmarshal(data, &lottery); err != nil {
			return nil, fmt.Errorf("UnmarshalAcquisitionConditionResponse: Cannot read lottery: %w", err)
		}
		return lottery, nil
	case "normal":
		var normal NormalAcquisitionConditionResponse
		if err := json.Unmarshal(data, &normal); err != nil {
			return nil, fmt.Errorf("UnmarshalAcquisitionConditionResponse: Cannot read normal: %w", err)
		}
		return normal, nil
	case "referral":
		var referral ReferralAcquisitionConditionResponse
		if err := json.Unmarshal(data, &referral); err != nil {
			return nil, fmt.Errorf("UnmarshalAcquisitionConditionResponse: Cannot read referral: %w", err)
		}
		return referral, nil

	default:
		var unknown UnknownAcquisitionConditionResponse
		unknown.Type = discriminator
		unknown.Raw = raw
		return unknown, nil
	}
}
