/**
 * LINE Messaging API
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

//go:generate python3 ../../generate-code.py
package messaging_api

// Sender
// Change icon and display name

type Sender struct {

	/**
	 * Display name. Certain words such as `LINE` may not be used.
	 */
	Name string `json:"name,omitempty"`

	/**
	 * URL of the image to display as an icon when sending a message
	 */
	IconUrl string `json:"iconUrl,omitempty"`
}
