/**
 * LINE Messaging API
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

//go:generate python3 ../../generate-code.py
package messaging_api

import (
	"encoding/json"
	"fmt"
)

// ValidateMessageRequest
// ValidateMessageRequest

type ValidateMessageRequest struct {

	/**
	 * Array of message objects to validate (Required)
	 */
	Messages []MessageInterface `json:"messages"`
}

func (cr *ValidateMessageRequest) UnmarshalJSON(data []byte) error {
	var raw map[string]json.RawMessage
	err := json.Unmarshal(data, &raw)
	if err != nil {
		return err
	}

	var rawmessages []json.RawMessage
	err = json.Unmarshal(raw["messages"], &rawmessages)
	if err != nil {
		return err
	}

	for _, data := range rawmessages {
		e, err := UnmarshalMessage(data)
		if err != nil {
			return fmt.Errorf("JSON parse error in UnmarshalMessage: %w, body: %s", err, string(data))
		}
		cr.Messages = append(cr.Messages, e)
	}

	return nil
}

// MarshalJSON customizes the JSON serialization of the ValidateMessageRequest struct.
func (r *ValidateMessageRequest) MarshalJSON() ([]byte, error) {

	newMessages := make([]MessageInterface, len(r.Messages))
	for i, v := range r.Messages {
		newMessages[i] = setDiscriminatorPropertyMessage(v)
	}

	type Alias ValidateMessageRequest
	return json.Marshal(&struct {
		*Alias

		Messages []MessageInterface `json:"messages"`
	}{
		Alias: (*Alias)(r),

		Messages: newMessages,
	})
}
