/**
 * LINE Messaging API
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

//go:generate python3 ../../generate-code.py
package messaging_api

/*
 * Font size in the `size` property of the Flex span component. You can specify the size in pixels or with a keyword. FlexSpanSize just provides only keywords.
 */

// FlexSpanSize type
type FlexSpanSize string

// FlexSpanSize constants
const (
	FlexSpanSize_XXS FlexSpanSize = "xxs"

	FlexSpanSize_XS FlexSpanSize = "xs"

	FlexSpanSize_SM FlexSpanSize = "sm"

	FlexSpanSize_MD FlexSpanSize = "md"

	FlexSpanSize_LG FlexSpanSize = "lg"

	FlexSpanSize_XL FlexSpanSize = "xl"

	FlexSpanSize_XXL FlexSpanSize = "xxl"

	FlexSpanSize__3XL FlexSpanSize = "3xl"

	FlexSpanSize__4XL FlexSpanSize = "4xl"

	FlexSpanSize__5XL FlexSpanSize = "5xl"
)
