/**
 * LINE Messaging API
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

//go:generate python3 ../../generate-code.py
package messaging_api

import (
	"encoding/json"
)

// EmojiSubstitutionObject
// An object representing a emoji substitution.
// https://developers.line.biz/en/reference/messaging-api/#text-message-v2-emoji-object
type EmojiSubstitutionObject struct {
	SubstitutionObject

	/**
	 * Get ProductId
	 */
	ProductId string `json:"productId"`

	/**
	 * Get EmojiId
	 */
	EmojiId string `json:"emojiId"`
}

// MarshalJSON customizes the JSON serialization of the EmojiSubstitutionObject struct.
func (r *EmojiSubstitutionObject) MarshalJSON() ([]byte, error) {

	type Alias EmojiSubstitutionObject
	return json.Marshal(&struct {
		*Alias

		Type string `json:"type"`
	}{
		Alias: (*Alias)(r),

		Type: "emoji",
	})
}
