/**
 * LINE Messaging API
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

//go:generate python3 ../../generate-code.py
package messaging_api

// MessageQuotaResponse
// MessageQuotaResponse
// https://developers.line.biz/en/reference/messaging-api/#get-quota
type MessageQuotaResponse struct {

	/**
	 * Get Type
	 */
	Type QuotaType `json:"type"`

	/**
	 * The target limit for sending messages in the current month. This property is returned when the `type` property has a value of `limited`.
	 */
	Value int64 `json:"value"`
}

func NewMessageQuotaResponse(

	Type QuotaType,

) *MessageQuotaResponse {
	e := &MessageQuotaResponse{}

	e.Type = Type

	return e
}
