/**
 * LINE Messaging API
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

//go:generate python3 ../../generate-code.py
package messaging_api

import (
	"encoding/json"
)

// PostbackAction
// PostbackAction

type PostbackAction struct {
	Action

	/**
	 * Label for the action.
	 */
	Label string `json:"label,omitempty"`

	/**
	 * Get Data
	 */
	Data string `json:"data,omitempty"`

	/**
	 * Get DisplayText
	 */
	DisplayText string `json:"displayText,omitempty"`

	/**
	 * Get Text
	 */
	Text string `json:"text,omitempty"`

	/**
	 * Get InputOption
	 */
	InputOption PostbackActionINPUT_OPTION `json:"inputOption,omitempty"`

	/**
	 * Get FillInText
	 */
	FillInText string `json:"fillInText,omitempty"`
}

func NewPostbackAction() *PostbackAction {
	e := &PostbackAction{}

	e.Type = "postback"

	return e
}

// MarshalJSON customizes the JSON serialization of the PostbackAction struct.
func (r *PostbackAction) MarshalJSON() ([]byte, error) {

	type Alias PostbackAction
	return json.Marshal(&struct {
		*Alias

		Type string `json:"type,omitempty"`
	}{
		Alias: (*Alias)(r),

		Type: "postback",
	})
}

// PostbackActionINPUT_OPTION type

type PostbackActionINPUT_OPTION string

// PostbackActionINPUT_OPTION constants
const (
	PostbackActionINPUT_OPTION_CLOSE_RICH_MENU PostbackActionINPUT_OPTION = "closeRichMenu"

	PostbackActionINPUT_OPTION_OPEN_RICH_MENU PostbackActionINPUT_OPTION = "openRichMenu"

	PostbackActionINPUT_OPTION_OPEN_KEYBOARD PostbackActionINPUT_OPTION = "openKeyboard"

	PostbackActionINPUT_OPTION_OPEN_VOICE PostbackActionINPUT_OPTION = "openVoice"
)
