/**
 * LINE Messaging API
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

//go:generate python3 ../../generate-code.py
package messaging_api

// PnpTemplatedButton
// PnpTemplatedButton
// https://developers.line.biz/en/reference/line-notification-messages/#send-line-notification-message-template-buttons
type PnpTemplatedButton struct {

	/**
	 * Specify the key of the button you want to include. For available keys, see https://developers.line.biz/en/docs/partner-docs/line-notification-messages/template/#buttons  (Required)
	 */
	ButtonKey string `json:"buttonKey"`

	/**
	 * URL of the page to be opened when the user presses the button. (Required)
	 */
	Url string `json:"url"`
}
