/**
 * LIFF server API
 * LIFF Server API.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

//go:generate python3 ../../generate-code.py
package liff

// LiffView
// LiffView
// https://developers.line.biz/en/reference/liff-server/#add-liff-app
type LiffView struct {

	/**
	 * Size of the LIFF app view. Specify one of these values: - compact - tall - full  (Required)
	 */
	Type LiffViewTYPE `json:"type"`

	/**
	 * Endpoint URL. This is the URL of the web app that implements the LIFF app (e.g. https://example.com). Used when the LIFF app is launched using the LIFF URL. The URL scheme must be https. URL fragments (#URL-fragment) can&#39;t be specified.  (Required)
	 */
	Url string `json:"url"`

	/**
	 * `true` to use the LIFF app in modular mode. When in modular mode, the action button in the header is not displayed.
	 */
	ModuleMode bool `json:"moduleMode"`
}

func NewLiffView(

	Type LiffViewTYPE,

	Url string,

) *LiffView {
	e := &LiffView{}

	e.Type = Type

	e.Url = Url

	return e
}

// LiffViewTYPE type
/* Size of the LIFF app view. Specify one of these values: - compact - tall - full  */
type LiffViewTYPE string

// LiffViewTYPE constants
const (
	LiffViewTYPE_COMPACT LiffViewTYPE = "compact"

	LiffViewTYPE_TALL LiffViewTYPE = "tall"

	LiffViewTYPE_FULL LiffViewTYPE = "full"
)
