/**
 * LIFF server API
 * LIFF Server API.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

//go:generate python3 ../../generate-code.py
package liff

// UpdateLiffAppRequest
// UpdateLiffAppRequest
// https://developers.line.biz/en/reference/liff-server/#add-liff-app
type UpdateLiffAppRequest struct {

	/**
	 * Get View
	 */
	View *UpdateLiffView `json:"view,omitempty"`

	/**
	 * Name of the LIFF app.  The LIFF app name can&#39;t include \&quot;LINE\&quot; or similar strings, or inappropriate strings.
	 */
	Description string `json:"description,omitempty"`

	/**
	 * Get Features
	 */
	Features *LiffFeatures `json:"features,omitempty"`

	/**
	 * How additional information in LIFF URLs is handled. Specify `concat`.
	 */
	PermanentLinkPattern string `json:"permanentLinkPattern,omitempty"`

	/**
	 * Get Scope
	 */
	Scope []LiffScope `json:"scope,omitempty"`

	/**
	 * Get BotPrompt
	 */
	BotPrompt LiffBotPrompt `json:"botPrompt,omitempty"`
}
