/**
 * LINE Messaging API(Insight)
 * This document describes LINE Messaging API(Insight).
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

//go:generate python3 ../../generate-code.py
package insight

// GetRichMenuInsightSummaryResponse
// Summary of impression and click statistics for a rich menu created via the Messaging API.

type GetRichMenuInsightSummaryResponse struct {

	/**
	 * Rich menu ID. (Required)
	 */
	RichMenuId string `json:"richMenuId"`

	/**
	 * Start date (JST) of the period actually covered by the returned metrics. Format: yyyyMMdd (e.g. 20260213).
	 */
	MetricsFrom string `json:"metricsFrom,omitempty"`

	/**
	 * End date (JST) of the period actually covered by the returned metrics. Format: yyyyMMdd (e.g. 20260215).
	 */
	MetricsTo string `json:"metricsTo,omitempty"`

	/**
	 * Get Impression
	 */
	Impression *GetRichMenuInsightSummaryResponseImpression `json:"impression,omitempty"`

	/**
	 * Click metrics for each tappable area of the rich menu.
	 */
	Clicks []GetRichMenuInsightSummaryResponseClick `json:"clicks,omitempty"`
}
