/**
 * LINE Messaging API(Insight)
 * This document describes LINE Messaging API(Insight).
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

//go:generate python3 ../../generate-code.py
package insight

// GetMessageEventResponseOverview
// Summary of message statistics.

type GetMessageEventResponseOverview struct {

	/**
	 * Request ID.
	 */
	RequestId string `json:"requestId,omitempty"`

	/**
	 * UNIX timestamp for message delivery time in seconds.
	 */
	Timestamp int64 `json:"timestamp"`

	/**
	 * Number of messages delivered. This property shows values of less than 20. However, if all messages have not been sent, it will be null.
	 */
	Delivered int64 `json:"delivered"`

	/**
	 * Number of users who opened the message, meaning they displayed at least 1 bubble.
	 */
	UniqueImpression int64 `json:"uniqueImpression"`

	/**
	 * Number of users who opened any URL in the message.
	 */
	UniqueClick int64 `json:"uniqueClick"`

	/**
	 * Number of users who started playing any video or audio in the message.
	 */
	UniqueMediaPlayed int64 `json:"uniqueMediaPlayed"`

	/**
	 * Number of users who played the entirety of any video or audio in the message.
	 */
	UniqueMediaPlayed100Percent int64 `json:"uniqueMediaPlayed100Percent"`
}

func NewGetMessageEventResponseOverview() *GetMessageEventResponseOverview {
	e := &GetMessageEventResponseOverview{}

	return e
}
