/**
 * LINE Messaging API(Insight)
 * This document describes LINE Messaging API(Insight).
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

//go:generate python3 ../../generate-code.py
package insight

// GetMessageEventResponseClick
// GetMessageEventResponseClick

// Deprecated: Use OpenAPI based classes instead.
type GetMessageEventResponseClick struct {

	/**
	 * The URL&#39;s serial number.
	 */
	Seq int32 `json:"seq"`

	/**
	 * URL.
	 */
	Url string `json:"url,omitempty"`

	/**
	 * Number of times the URL was opened.
	 */
	Click int64 `json:"click"`

	/**
	 * Number of users that opened the URL.
	 */
	UniqueClick int64 `json:"uniqueClick"`

	/**
	 * Number of users who opened this url through any link in the message. If a message contains two links to the same URL and a user opens both links, they&#39;re counted only once.
	 */
	UniqueClickOfRequest int64 `json:"uniqueClickOfRequest"`
}
