/**
 * LINE Messaging API(Insight)
 * This document describes LINE Messaging API(Insight).
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

//go:generate python3 ../../generate-code.py
package insight

// GetStatisticsPerUnitResponseClick
// GetStatisticsPerUnitResponseClick
// https://developers.line.biz/en/reference/messaging-api/#get-statistics-per-unit-response
// Deprecated: Use OpenAPI based classes instead.
type GetStatisticsPerUnitResponseClick struct {

	/**
	 * The URL&#39;s serial number. (Required)
	 */
	Seq int64 `json:"seq"`

	/**
	 * URL. (Required)
	 */
	Url string `json:"url"`

	/**
	 * Number of times the URL in the bubble was opened.
	 */
	Click int64 `json:"click"`

	/**
	 * Number of users that opened the URL in the bubble.
	 */
	UniqueClick int64 `json:"uniqueClick"`

	/**
	 * Number of users who opened this url through any link in the message. If another message bubble contains the same URL and a user opens both links, it&#39;s counted only once.
	 */
	UniqueClickOfRequest int64 `json:"uniqueClickOfRequest"`
}
