/**
 * LINE Messaging API(Insight)
 * This document describes LINE Messaging API(Insight).
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

//go:generate python3 ../../generate-code.py
package insight

// GetRichMenuInsightSummaryResponseMetrics
// Aggregated number of events and unique users over the whole period.

type GetRichMenuInsightSummaryResponseMetrics struct {

	/**
	 * Number of impressions or clicks. (Required)
	 */
	Count int64 `json:"count"`

	/**
	 * Approximate number of unique users who triggered an impression or click. (Required)
	 */
	UniqueUsers int64 `json:"uniqueUsers"`
}
