/**
 * Channel Access Token API
 * This document describes Channel Access Token API.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

//go:generate python3 ../../generate-code.py
package channel_access_token

// VerifyChannelAccessTokenResponse
// Verification result

type VerifyChannelAccessTokenResponse struct {

	/**
	 * The channel ID for which the channel access token was issued. (Required)
	 */
	ClientId string `json:"client_id"`

	/**
	 * Number of seconds before the channel access token expires. (Required)
	 */
	ExpiresIn int64 `json:"expires_in"`

	/**
	 * Permissions granted to the channel access token.
	 */
	Scope string `json:"scope,omitempty"`
}

func NewVerifyChannelAccessTokenResponse(

	ClientId string,

	ExpiresIn int64,

) *VerifyChannelAccessTokenResponse {
	e := &VerifyChannelAccessTokenResponse{}

	e.ClientId = ClientId

	e.ExpiresIn = ExpiresIn

	return e
}
