/**
 * Channel Access Token API
 * This document describes Channel Access Token API.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

//go:generate python3 ../../generate-code.py
package channel_access_token

// ErrorResponse
// Error response of the Channel access token

type ErrorResponse struct {

	/**
	 * Error summary
	 */
	Error string `json:"error,omitempty"`

	/**
	 * Details of the error. Not returned in certain situations.
	 */
	ErrorDescription string `json:"error_description,omitempty"`
}

func NewErrorResponse() *ErrorResponse {
	e := &ErrorResponse{}

	return e
}
