/**
 * Mission Stickers API
 * This document describes LINE Mission Stickers API.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

//go:generate python3 ../../generate-code.py
package shop

// MissionStickerRequest
// Send mission stickers (v3)
// https://developers.line.biz/en/reference/partner-docs/#send-mission-stickers-v3
type MissionStickerRequest struct {

	/**
	 * Destination user ID (Required)
	 */
	To string `json:"to"`

	/**
	 * Package ID for a set of stickers (Required)
	 */
	ProductId string `json:"productId"`

	/**
	 * `STICKER` (Required)
	 */
	ProductType string `json:"productType"`

	/**
	 * `false` (Required)
	 */
	SendPresentMessage bool `json:"sendPresentMessage"`
}
