/**
 * Membership API
 * This document describes LINE Official Account Membership API.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

//go:generate python3 ../../generate-code.py
package membership

// ErrorResponse
// ErrorResponse

type ErrorResponse struct {

	/**
	 * Error message (Required)
	 */
	Message string `json:"message"`

	/**
	 * Get Details
	 */
	Details []string `json:"details"`
}
