/**
 * Webhook Type Definition
 * Webhook event definition of the LINE Messaging API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

//go:generate python3 ../../generate-code.py
package webhook

// PnpDelivery
// A delivery object containing a hashed phone number string or a string specified by `X-Line-Delivery-Tag` header

type PnpDelivery struct {

	/**
	 * A hashed phone number string or a string specified by `X-Line-Delivery-Tag` header (Required)
	 */
	Data string `json:"data"`
}
