/**
 * Webhook Type Definition
 * Webhook event definition of the LINE Messaging API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

//go:generate python3 ../../generate-code.py
package webhook

import (
	"encoding/json"
)

// DetachedModuleContent
// DetachedModuleContent

type DetachedModuleContent struct {
	ModuleContent

	/**
	 * Detached LINE Official Account bot user ID (Required)
	 */
	BotId string `json:"botId"`

	/**
	 * Reason for detaching (Required)
	 */
	Reason DetachedModuleContentREASON `json:"reason"`
}

// MarshalJSON customizes the JSON serialization of the DetachedModuleContent struct.
func (r *DetachedModuleContent) MarshalJSON() ([]byte, error) {

	type Alias DetachedModuleContent
	return json.Marshal(&struct {
		*Alias

		Type string `json:"type"`
	}{
		Alias: (*Alias)(r),

		Type: "detached",
	})
}

// DetachedModuleContentREASON type
/* Reason for detaching */
type DetachedModuleContentREASON string

// DetachedModuleContentREASON constants
const (
	DetachedModuleContentREASON_BOT_DELETED DetachedModuleContentREASON = "bot_deleted"
)
