/**
 * Webhook Type Definition
 * Webhook event definition of the LINE Messaging API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

//go:generate python3 ../../generate-code.py
package webhook

// BeaconContent
// BeaconContent

type BeaconContent struct {

	/**
	 * Hardware ID of the beacon that was detected (Required)
	 */
	Hwid string `json:"hwid"`

	/**
	 * Type of beacon event. (Required)
	 */
	Type BeaconContentTYPE `json:"type"`

	/**
	 * Device message of beacon that was detected.
	 */
	Dm string `json:"dm,omitempty"`
}

// BeaconContentTYPE type
/* Type of beacon event. */
type BeaconContentTYPE string

// BeaconContentTYPE constants
const (
	BeaconContentTYPE_ENTER BeaconContentTYPE = "enter"

	BeaconContentTYPE_BANNER BeaconContentTYPE = "banner"

	BeaconContentTYPE_STAY BeaconContentTYPE = "stay"
)
