/**
 * Webhook Type Definition
 * Webhook event definition of the LINE Messaging API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

//go:generate python3 ../../generate-code.py
package webhook

import (
	"encoding/json"
)

// UserMentionee
// Mentioned target is user

type UserMentionee struct {
	Mentionee

	/**
	 * Index position of the user mention for a character in text, with the first character being at position 0. (Required)
	 */
	Index int32 `json:"index"`

	/**
	 * The length of the text of the mentioned user. For a mention @example, 8 is the length. (Required)
	 */
	Length int32 `json:"length"`

	/**
	 * User ID of the mentioned user. Only included if mention.mentions[].type is user and the user consents to the LINE Official Account obtaining their user profile information.
	 */
	UserId string `json:"userId,omitempty"`
}

// MarshalJSON customizes the JSON serialization of the UserMentionee struct.
func (r *UserMentionee) MarshalJSON() ([]byte, error) {

	type Alias UserMentionee
	return json.Marshal(&struct {
		*Alias

		Type string `json:"type"`
	}{
		Alias: (*Alias)(r),

		Type: "user",
	})
}
