/**
 * Webhook Type Definition
 * Webhook event definition of the LINE Messaging API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

//go:generate python3 ../../generate-code.py
package webhook

import (
	"encoding/json"
)

// JoinedMembershipContent
// JoinedMembershipContent

type JoinedMembershipContent struct {
	MembershipContent

	/**
	 * The ID of the membership that the user joined. This is defined for each membership. (Required)
	 */
	MembershipId int32 `json:"membershipId"`
}

// MarshalJSON customizes the JSON serialization of the JoinedMembershipContent struct.
func (r *JoinedMembershipContent) MarshalJSON() ([]byte, error) {

	type Alias JoinedMembershipContent
	return json.Marshal(&struct {
		*Alias

		Type string `json:"type"`
	}{
		Alias: (*Alias)(r),

		Type: "joined",
	})
}
