/**
 * Webhook Type Definition
 * Webhook event definition of the LINE Messaging API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

//go:generate python3 ../../generate-code.py
package webhook

import (
	"encoding/json"
)

// FileMessageContent
// FileMessageContent

type FileMessageContent struct {
	MessageContent

	/**
	 * Message ID (Required)
	 */
	Id string `json:"id"`

	/**
	 * File name (Required)
	 */
	FileName string `json:"fileName"`

	/**
	 * File size in bytes (Required)
	 */
	FileSize int32 `json:"fileSize"`
}

// MarshalJSON customizes the JSON serialization of the FileMessageContent struct.
func (r *FileMessageContent) MarshalJSON() ([]byte, error) {

	type Alias FileMessageContent
	return json.Marshal(&struct {
		*Alias

		Type string `json:"type"`
	}{
		Alias: (*Alias)(r),

		Type: "file",
	})
}
