/**
 * LINE Messaging API
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

//go:generate python3 ../../generate-code.py
package manage_audience

/*
 * Job status
 */

// AudienceGroupJobStatus type
type AudienceGroupJobStatus string

// AudienceGroupJobStatus constants
const (
	AudienceGroupJobStatus_QUEUED AudienceGroupJobStatus = "QUEUED"

	AudienceGroupJobStatus_WORKING AudienceGroupJobStatus = "WORKING"

	AudienceGroupJobStatus_FINISHED AudienceGroupJobStatus = "FINISHED"

	AudienceGroupJobStatus_FAILED AudienceGroupJobStatus = "FAILED"
)
