/**
 * LINE Messaging API
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

//go:generate python3 ../../generate-code.py
package manage_audience

// CreateAudienceGroupRequest
// Create audience for uploading user IDs (by JSON)
// https://developers.line.biz/en/reference/messaging-api/#create-upload-audience-group
// Deprecated: Use OpenAPI based classes instead.
type CreateAudienceGroupRequest struct {

	/**
	 * The audience&#39;s name. This is case-insensitive, meaning AUDIENCE and audience are considered identical. Max character limit: 120
	 */
	Description string `json:"description,omitempty"`

	/**
	 * To specify recipients by IFAs: set true. To specify recipients by user IDs: set false or omit isIfaAudience property.
	 */
	IsIfaAudience bool `json:"isIfaAudience"`

	/**
	 * The description to register for the job (in jobs[].description).
	 */
	UploadDescription string `json:"uploadDescription,omitempty"`

	/**
	 * An array of user IDs or IFAs. Max number: 10,000
	 */
	Audiences []Audience `json:"audiences,omitempty"`
}
