/**
 * LINE Messaging API
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

//go:generate python3 ../../generate-code.py
package manage_audience

/*
 * Audience group type
 */

// AudienceGroupType type
type AudienceGroupType string

// AudienceGroupType constants
const (
	AudienceGroupType_UPLOAD AudienceGroupType = "UPLOAD"

	AudienceGroupType_CLICK AudienceGroupType = "CLICK"

	AudienceGroupType_IMP AudienceGroupType = "IMP"

	AudienceGroupType_CHAT_TAG AudienceGroupType = "CHAT_TAG"

	AudienceGroupType_FRIEND_PATH AudienceGroupType = "FRIEND_PATH"

	AudienceGroupType_RESERVATION AudienceGroupType = "RESERVATION"

	AudienceGroupType_APP_EVENT AudienceGroupType = "APP_EVENT"

	AudienceGroupType_VIDEO_VIEW AudienceGroupType = "VIDEO_VIEW"

	AudienceGroupType_WEBTRAFFIC AudienceGroupType = "WEBTRAFFIC"

	AudienceGroupType_IMAGE_CLICK AudienceGroupType = "IMAGE_CLICK"

	AudienceGroupType_RICHMENU_IMP AudienceGroupType = "RICHMENU_IMP"

	AudienceGroupType_RICHMENU_CLICK AudienceGroupType = "RICHMENU_CLICK"
)
