/**
 * LINE Messaging API
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

//go:generate python3 ../../generate-code.py
package manage_audience

/*
 * Failed type
 */

// AudienceGroupJobFailedType type
type AudienceGroupJobFailedType string

// AudienceGroupJobFailedType constants
const (
	AudienceGroupJobFailedType_INTERNAL_ERROR AudienceGroupJobFailedType = "INTERNAL_ERROR"

	AudienceGroupJobFailedType_AUDIENCE_GROUP_AUDIENCE_INSUFFICIENT AudienceGroupJobFailedType = "AUDIENCE_GROUP_AUDIENCE_INSUFFICIENT"
)
