/**
 * LINE Messaging API
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

//go:generate python3 ../../generate-code.py
package manage_audience

// CreateImpBasedAudienceGroupRequest
// Create audience for impression-based retargeting
// https://developers.line.biz/en/reference/messaging-api/#create-imp-audience-group
type CreateImpBasedAudienceGroupRequest struct {

	/**
	 * The audience&#39;s name. This is case-insensitive, meaning `AUDIENCE` and `audience` are considered identical. Max character limit: 120
	 */
	Description string `json:"description,omitempty"`

	/**
	 * The request ID of a broadcast or narrowcast message sent in the past 60 days. Each Messaging API request has a request ID.
	 */
	RequestId string `json:"requestId,omitempty"`
}
