/**
 * LINE Messaging API
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

//go:generate python3 ../../generate-code.py
package manage_audience

// AudienceGroupJob
// Audience group job
// https://developers.line.biz/en/reference/messaging-api/#get-audience-group
type AudienceGroupJob struct {

	/**
	 * A job ID.
	 */
	AudienceGroupJobId int64 `json:"audienceGroupJobId"`

	/**
	 * An audience ID.
	 */
	AudienceGroupId int64 `json:"audienceGroupId"`

	/**
	 * The job&#39;s description.
	 */
	Description string `json:"description,omitempty"`

	/**
	 * Get Type
	 */
	Type AudienceGroupJobType `json:"type,omitempty"`

	/**
	 * Get JobStatus
	 */
	JobStatus AudienceGroupJobStatus `json:"jobStatus,omitempty"`

	/**
	 * Get FailedType
	 */
	FailedType AudienceGroupJobFailedType `json:"failedType,omitempty"`

	/**
	 * The number of accounts (recipients) that were added or removed.
	 */
	AudienceCount int64 `json:"audienceCount"`

	/**
	 * When the job was created (in UNIX time).
	 */
	Created int64 `json:"created"`
}

func NewAudienceGroupJob() *AudienceGroupJob {
	e := &AudienceGroupJob{}

	return e
}
