/**
 * LINE Messaging API
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

//go:generate python3 ../../generate-code.py
package manage_audience

/*
 * Status
 */

// AudienceGroupStatus type
type AudienceGroupStatus string

// AudienceGroupStatus constants
const (
	AudienceGroupStatus_IN_PROGRESS AudienceGroupStatus = "IN_PROGRESS"

	AudienceGroupStatus_READY AudienceGroupStatus = "READY"

	AudienceGroupStatus_FAILED AudienceGroupStatus = "FAILED"

	AudienceGroupStatus_EXPIRED AudienceGroupStatus = "EXPIRED"

	AudienceGroupStatus_INACTIVE AudienceGroupStatus = "INACTIVE"

	AudienceGroupStatus_ACTIVATING AudienceGroupStatus = "ACTIVATING"
)
